YDBOPS-10450 Adaptation of pre-collections (part 1)
ydb-platform/ydb-ansible pull request #44
Opened 2024-10-08 11:50 UTC by elabpro

1) Script for converting configs for main branch ( pre-collections-convert.py )
2) AlmaLinux9 support
3) Fix problem with formating storages

2024-10-10 11:27 UTC, VadimZud commented on roles/packages/tasks/main.yaml
>  - name: configure unconfigured packages
Let's create `config_apt.yaml` `config_dnf.yaml` tasks files and use one conditional `ansible.builtin.import_tasks` module

2024-10-10 11:48 UTC, VadimZud commented on roles/packages/tasks/main.yaml
> +  when: vars_for_distribution_version.repositories and ansible_distribution != "AlmaLinux"
Зашивать конкретную ОС с условие не очень удобно. Будут появляться новые ОС и условие будет неконтролируемо разрастаться. Лучше где-то в одном месте определить тип пакетной системы, сохранить его в переменную и использовать её

2024-10-10 11:49 UTC, VadimZud commented on roles/packages/tasks/main.yaml
> +  when: ansible_distribution != "AlmaLinux"
Может мы можем использовать здесь `ansible.builtin.package`, он уже умеет определять пакетную систему

2024-10-10 11:52 UTC, VadimZud commented on roles/system/tasks/main.yaml
> +  when: ansible_distribution != 'AlmaLinux'
Также не стоит Зашивать операционную систему здесь. Лучше где-то централизованно определить поддержку системой `systemd-timesyncd`, запомнить в переменной и использовать переменную. Возможно хорошим решение будет кастомный ansible_fact

2024-10-10 11:55 UTC, VadimZud commented on roles/ydbd/tasks/main.yaml
> +  when: ansible_distribution != 'AlmaLinux'
Аналогично всем осталным замечаниям про конкретную ОС в условиях

2024-10-10 11:59 UTC, VadimZud commented on roles/ydbd_static/tasks/main.yaml
> +  any_errors_fatal: true
Давай останавливать сторадж только если пользователь действительно согласился форматировать диски.

2024-10-10 12:01 UTC, VadimZud requested changes
Пока не поревьювил `pre-collections-convert.py`, еще вернусь к нему

2024-10-10 13:48 UTC, elabpro commented on roles/packages/tasks/main.yaml
>  - name: configure unconfigured packages
Все делается проще - есть ansible_os_family, перевел на него
https://techviewleo.com/list-of-ansible-os-family-distributions-facts/

2024-10-11 09:54 UTC, elabpro commented on roles/packages/tasks/main.yaml
>  - name: configure unconfigured packages
Давай это сделаем в следующих изменениях, это не блокер

2024-10-11 09:56 UTC, elabpro commented on roles/packages/tasks/main.yaml
> +  when: ansible_distribution != "AlmaLinux"
Это требуется дополнительных проверок, так как ранее встречал случаи , где он не работал корректно

2024-10-11 10:28 UTC, artgromov requested changes

2024-10-11 10:28 UTC, artgromov commented on roles/system/tasks/main.yaml
> +        name: chrony
в каких поддерживаемых на текущий момент дистрибутивах нет timesyncd и нужно ставить chrony?

2024-10-11 10:28 UTC, artgromov commented on roles/packages/tasks/main.yaml
> +  ansible.builtin.dnf:
что если эту таску и предыдущую заменить одной с использованием ansible.builtin.package и дистро-зависимых переменных?

2024-10-11 10:28 UTC, artgromov commented on roles/packages/tasks/main.yaml
> +  when: vars_for_distribution_version.configs and ansible_os_family == 'Debian'
Мы рискуем утонуть в этих условиях.

Давай сделаем в tasks отдельный файл на каждый пакетный менеджер (или пару пакетный менеджер + менеджер зависимостей пакетов). И будем импортировать таску исходя из os family.

2024-10-11 10:28 UTC, artgromov commented on roles/system/tasks/main.yaml
> +  when: ansible_os_family != 'Debian'
Кажется, не очень корректно опираться на это условие. Мы внутри используем timesyncd. Если его нет, имеет смысл попробовать его поставить и везде использовать.

2024-10-11 10:31 UTC, VadimZud requested changes

2024-10-11 10:31 UTC, VadimZud commented on pre-collections-convert.py
> +def read_hosts(file_path):
The hosts file is an INI file. You don't need to do manual parsing. Use an existing Python INI file parser.

2024-10-11 10:31 UTC, VadimZud commented on pre-collections-convert.py
> +        y = yaml.safe_dump(inv, default_flow_style=False).replace(r"''", '')
`safe_dump` generates valid YAML. Why is replacement needed?

2024-10-11 11:31 UTC, VadimZud commented on pre-collections-convert.py
> +    for host_type in hosts:
You can create real children groups in group `ydb` for `host_type`s.

2024-10-11 11:34 UTC, VadimZud commented on pre-collections-convert.py
> +    h = {}
`h = set()` is more suitable

2024-10-11 11:37 UTC, VadimZud commented on pre-collections-convert.py
> +        for host in hosts[host_type]:
`h.update(hosts[host_type])` can be used with `set`

2024-10-14 07:59 UTC, elabpro commented on pre-collections-convert.py
> +        y = yaml.safe_dump(inv, default_flow_style=False).replace(r"''", '')
safe_dump doesn't generate output like:
name:<empty value> (ydb-node01:)
it will generate:
name:''

2024-10-29 14:13 UTC, closed without merging