YDBOPS-10450 Merge pre-collection playbooks into main
ydb-platform/ydb-ansible pull request #46
Opened 2024-10-28 10:46 UTC by elabpro

1) Support for different OS:
    - Ubuntu 24.04
    - Debian 11.11, 12.7
    - AstraLinux 1.7
    - AlmaLinux 8,9
    - RedHat 9
    - RedOS 7
2) Move OS dependent part into role packages
3) Install custom CA certificates for export/import into custom S3 storage
4) availability_mode for restart
5) healthcheck with user/pass 
6) Install system with releases (/opt/ydb/releases folder)
7) Reviewed kernel settings

2024-10-28 12:25 UTC, artgromov commented on playbooks/install_ca.yaml
> +        name: ydb_platform.ydb.install_ca
Зачем для этого отдельный плейбук с одной ролью если саму роль с аргументами можно запустить с пом-ю ansible-runner?

2024-10-29 07:10 UTC, elabpro commented on playbooks/install_ca.yaml
> +        name: ydb_platform.ydb.install_ca
Это было сделано для удобства обучения по курсу Лопатина

2024-10-29 07:48 UTC, artgromov commented on playbooks/install_ca.yaml
> +        name: ydb_platform.ydb.install_ca
Может вынести все, что касается курса в отдельную папочку с примерами в https://github.com/ydb-platform/ydb-ansible-examples?

2024-10-29 13:34 UTC, elabpro commented on playbooks/install_ca.yaml
> +        name: ydb_platform.ydb.install_ca
удалил плейбук, показал как запускать роль без плейбука

2024-10-29 13:35 UTC, artgromov approved these changes

2024-10-29 14:51 UTC, VadimZud requested changes

2024-10-29 14:51 UTC, VadimZud commented on playbooks/install_dynamic.yaml
> +- hosts: "{{ playbook_hosts | default('ydbd') }}"
Почему вдруг получилось такое изменение?

2024-10-30 05:48 UTC, elabpro commented on playbooks/install_dynamic.yaml
> +- hosts: "{{ playbook_hosts | default('ydbd') }}"
Опечатка, в начале переводил все на ydbd_static / ydbd_dynamic, потом откатывал. Исправил

2024-10-30 05:48 UTC, elabpro commented on plugins/modules/wait_healthcheck.py
> +            rc, stdout, stderr = ydb_cli(ydb_cmd)
Внес правки

2024-10-30 05:48 UTC, elabpro commented on roles/check_connectivity/defaults/main.yaml
> +  - 2136
+ добавил

2024-10-30 10:47 UTC, VadimZud approved these changes

2024-10-30 12:49 UTC, merged